import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  userProfileTop: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 120,
    minHeight: 380,
  },
  userProfileTopBg: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: null,
    height: null,
  },
  userProfileTopOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: null,
    height: null,
    backgroundColor: "#000000",
    opacity: 0.2,
  },
  userProfileInfoName: {
    marginTop: 16,
    color: "#ffffff",
    fontSize: 22,
    textAlign: "center",
  },
  userProfileInfoJobTitle: {
    marginTop: 4,
    color: "#ffffff",
    fontSize: 16,
    textAlign: "center",
    opacity: 0.7,
  },
  userProfileInfoLocation: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  userProfileInfoLocationText: {
    marginLeft: 4,
    color: "#ffffff",
    fontSize: 16,
    textAlign: "center",
    opacity: 0.7,
  },
  userProfileWidget: {
    alignSelf: "stretch",
    margin: 24,
    marginTop: 24,
    marginBottom: 24,
  },
  widget: {
    flexDirection: "row",
    flexGrow: 1,
    flexShrink: 0,
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    borderRadius: 8,
    paddingVertical: 8,
    minHeight: 60,
  },
  widgetItem: {
    flex: 1,
    justifyContent: "center",
    minWidth: 0,
    paddingVertical: 4,
    borderRightWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.5)",
  },
  widgetItemLast: {
    borderRightWidth: 0,
  },
  widgetItemLabel: {
    color: "#ffffff",
    fontSize: 14,
    textAlign: "center",
    opacity: 0.5,
  },
  widgetItemValue: {
    marginTop: 4,
    color: "#ffffff",
    fontSize: 16,
    textAlign: "center",
  },
  userProfileBody: {
    flexGrow: 1,
    paddingTop: 24,
    paddingBottom: 100,
  },
  flexB: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingHorizontal: 24,
  },
  btnA: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 46,
    minWidth: 130,
    maxWidth: "100%",
    paddingHorizontal: 24,
    backgroundColor: "#299cd1",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#299cd1",
    overflow: "hidden",
  },
  btnTextA: {
    color: "#ffffff",
    fontSize: 20,
  },
  btnB: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 46,
    minWidth: 130,
    maxWidth: "100%",
    paddingHorizontal: 24,
    backgroundColor: "#008000",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#ffffff00",
    overflow: "hidden",
  },
  btnTextB: {
    color: "#ffffffff",
    fontSize: 20,
  },
  typography: {
    fontSize: 16,
  },
  sectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 30,
    paddingHorizontal: 24,
  },
  sectionHeadingText: {
    fontSize: 26,
    color: "#1c1c1c",
  },
  sectionContent: {
    paddingHorizontal: 24,
    paddingVertical: 8,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: "gray",
    marginVertical: 20,
    width: "90%",
    alignSelf: "center",
  },
  PostText: {
    fontSize: 26,
    color: "#1c1c1c",
    alignSelf: "center",
    marginBottom: 20,
  },
  input: {
    height: "auto",
    width: "90%",
    margin: 12,
    borderWidth: 1,
    padding: 10,
    borderRadius: 10,
    borderColor: "#ccc",
    alignSelf: "center",
    fontSize: 16,
  },
  inputAge: {
    height: "auto",
    width: "30%",
    margin: 12,
    borderWidth: 1,
    padding: 10,
    borderRadius: 10,
    borderColor: "#ccc",
    alignSelf: "flex-start",
    fontSize: 16,
    textAlign: "center",
  },
  inputInfo: {
    height: "auto",
    width: "90%",
    margin: 12,
    borderWidth: 1,
    padding: 10,
    borderRadius: 10,
    borderColor: "#ccc",
    alignSelf: "center",
    fontSize: 16,
  },
  subHeader: {
    fontSize: 15,
    fontWeight: "300",
    color: "#1c1c1c",
    alignSelf: "auto",
    marginBottom: 0,
  },
  baseText: {
    fontSize: 20,
    fontWeight: "400",
    color: "#7b7b7bff",
    alignSelf: "center",
    marginBottom: 10,
  },
  btnEdit: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 46,
    minWidth: 130,
    maxWidth: "100%",
    paddingHorizontal: 24,
    backgroundColor: "#ffffff00",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#032535",
    overflow: "hidden",
  },
  btnTextEdit: {
    color: "#032535",
    fontSize: 20,
  },
  button: {
    borderRadius: 10,
    alignSelf: "center",
    width: "50%",
    marginBottom: 20,
    //alignSelf: "flex-start",
  },
});

export default styles;
