import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  errorText: {
    color: "red",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
    marginTop: 6,
    textAlign: "center",
  },
  profileNameContainer: {
    position: "absolute",
    bottom: -140,
    padding: 10,
    borderRadius: 25,
    backgroundColor: "#303030e1",
    opacity: 0.9,
  },
  userProfileTop: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f0f0f0",
    width: "100%",
    position: "relative",
    top: 0,
    zIndex: 1,
  },
  profileImage: {
    width: "100%",
    height: 360,
    resizeMode: "cover",
  },
  userProfileInfoName: {
    color: "#f1f1f1",
    fontWeight: "bold",
    fontSize: 30,
    textAlign: "center",
    zIndex: 2,
  },
  userProfileInfoLocation: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
    marginHorizontal: 4,
  },
  userProfileInfoLocationText: {
    marginLeft: 4,
    color: "#ffffff",
    fontSize: 16,
    textAlign: "center",
    opacity: 0.7,
  },
  userProfileBody: {
    flexGrow: 1,
    paddingBottom: 100,
    marginTop: 160,
  },
  flexB: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingHorizontal: 24,
  },
  btnA: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 46,
    minWidth: 130,
    maxWidth: "100%",
    paddingHorizontal: 24,
    backgroundColor: "#299cd1",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#299cd1",
    overflow: "hidden",
  },
  btnTextA: {
    color: "#ffffff",
    fontSize: 20,
  },
  btnB: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 46,
    minWidth: 130,
    maxWidth: "100%",
    paddingHorizontal: 24,
    backgroundColor: "#008000",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#ffffff00",
    overflow: "hidden",
  },
  btnTextB: {
    color: "#ffffffff",
    fontSize: 20,
  },
  typography: {
    fontSize: 16,
  },
  sectionHeadingText: {
    paddingHorizontal: 24,
    fontSize: 20,
    textTransform: "uppercase",
    color: "#464646",
    letterSpacing: 1,
  },
  sectionContent: {
    paddingHorizontal: 24,
    paddingVertical: 8,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: "gray",
    marginVertical: 20,
    width: "90%",
    alignSelf: "center",
  },
  input: {
    height: "auto",
    width: "90%",
    margin: 12,
    borderWidth: 1,
    padding: 10,
    borderRadius: 10,
    borderColor: "#ccc",
    alignSelf: "center",
    fontSize: 16,
  },
  inputInfo: {
    height: "auto",
    width: "90%",
    margin: 12,
    borderWidth: 1,
    padding: 10,
    borderRadius: 10,
    borderColor: "#ccc",
    alignSelf: "center",
    fontSize: 16,
  },
  subHeader: {
    fontSize: 15,
    fontWeight: "300",
    color: "#1c1c1c",
    alignSelf: "auto",
    marginBottom: 0,
  },
  baseText: {
    fontSize: 20,
    fontWeight: "400",
    color: "#7b7b7bff",
    alignSelf: "center",
    marginBottom: 10,
  },
  button: {
    borderRadius: 10,
    alignSelf: "center",
    width: "50%",
    marginBottom: 20,
  },
  buttonSave: {
    backgroundColor: "#008000",
    borderRadius: 10,
    width: "80%",
  },
  buttonEdit: {
    borderWidth: 1,
    borderColor: "#032535",
    borderRadius: 10,
    width: "80%",
  },
  buttonSettings: {
    borderWidth: 1,
    borderRadius: 10,
    width: "80%",
  },
  buttonTextEdit: {
    color: "#032535",
  },
});

export default styles;
