import { StyleSheet } from "react-native";
import Constants from "expo-constants";
const styles = StyleSheet.create({
  input: {
    height: 40,
    width: "80%",
    margin: 12,
    borderWidth: 1,
    padding: 10,
    borderRadius: 10,
    borderColor: "#ccc",
    alignItems: "center",
    justifyContent: "center",
  },
  mediaButton: {
    margin: 12,
    borderWidth: 0.1,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    borderColor: "#ccc",
  },
  container: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  header: {
    fontSize: 20,
    margin: 12,
    marginTop: 50,
  },
  containerTouchable: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    borderColor: "#ccc",
    fontSize: 20,
    margin: 12,
    padding: 10,
    borderWidth: 1,
  },
  TextTouchable: {
    fontSize: 20,
    marginRight: 8,
  },
  divider: {
    width: "80%",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    borderRadius: 0,
    marginVertical: 10,
  },
  button: {
    width: "40%",
    height: 40,
    alignItems: "center",
    borderRadius: 20,
    marginBottom: 20,
    padding: 10,
    backgroundColor: "#007BFF",
    shadowColor: "rgba(0, 0, 0, 0.3)",
    shadowOpacity: 1,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 4,
    },
  },
  text: {
    color: "#fff",
  },
  locationContainer: {
    height: "90%",
    backgroundColor: "white",
    shadowColor: "black",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    padding: 8,
    borderRadius: 10,
    top: Constants.statusBarHeight,
    marginHorizontal: 10,
  },
  locationInput: {
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    margin: 10,
    shadowColor: "black",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  locationText: {
    fontSize: 20,
    marginHorizontal: 15,
    marginVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  // modal: {
  //   height: "50%",
  //   width: "50%",
  //   backgroundColor: "white",
  //   alignItems: "center",
  //   justifyContent: "center",
  //   borderRadius: 10,
  // }
});

export default styles;
